name: Update Geo Files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-geo-files:
    name: Update Geo Files

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download geo files
        run: |
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat -o GeoIP.dat
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat -o GeoSite.dat

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add GeoIP.dat GeoSite.dat
          git commit -m "Update Geo Files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
